package com.cedric.Eventra.enums;

public enum NotificationType {
    // Booking related
    NEW_BOOKING_REQUEST,
    BOOKING_REQUEST_ACCEPTED,
    BOOKING_REQUEST_REJECTED,
    BOOKING_PAYMENT_SUCCESSFUL,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED_BY_USER,
    BOOKING_CANCELLED_BY_PROVIDER,
    BOOKING_UPCOMING_REMINDER,
    BOOKING_COMPLETED,

    // User account related
    WELCOME_MESSAGE,
    PASSWORD_RESET_REQUEST,
    PROFILE_UPDATE,

    // General
    GENERAL_ANNOUNCEMENT
}
